apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes Heketi Service
  labels:
    deploy-heketi: support
    glusterfs: heketi-service
  name: heketi
  namespace: default
spec:
  ports:
  - name: heketi
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: heketi
  externalIPs:
  - 192.168.1.121
